import { getCrewUser, unauthorized } from "../../../db/auth";
import { getDatabase } from "../../../db";

async function ensureTable() { const database = getDatabase(); await database.batch([
  database.prepare(`CREATE TABLE IF NOT EXISTS cabin_defects (id INTEGER PRIMARY KEY AUTOINCREMENT, flight_no TEXT NOT NULL, aircraft_registration TEXT NOT NULL, equipment_type TEXT NOT NULL, defect_type TEXT NOT NULL, description TEXT NOT NULL, cabin_location TEXT NOT NULL, safety_hazard INTEGER NOT NULL DEFAULT 0, engineer_required INTEGER NOT NULL DEFAULT 0, mel_classification TEXT NOT NULL DEFAULT 'none', status TEXT NOT NULL DEFAULT 'open', engineer_notes TEXT NOT NULL DEFAULT '', reported_by TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, resolved_at TEXT)`),
  database.prepare(`CREATE INDEX IF NOT EXISTS idx_cabin_defects_flight_no ON cabin_defects(flight_no)`), database.prepare(`CREATE INDEX IF NOT EXISTS idx_cabin_defects_status ON cabin_defects(status)`), database.prepare(`CREATE INDEX IF NOT EXISTS idx_cabin_defects_equipment_type ON cabin_defects(equipment_type)`),
]); }
export async function GET(request: Request) { const user = await getCrewUser(request); if (!user) return unauthorized(); await ensureTable(); const rows = await getDatabase().prepare("SELECT id, flight_no AS flightNo, aircraft_registration AS aircraftRegistration, equipment_type AS equipmentType, defect_type AS defectType, description, cabin_location AS cabinLocation, safety_hazard AS safetyHazard, engineer_required AS engineerRequired, mel_classification AS melClassification, status, engineer_notes AS engineerNotes, reported_by AS reportedBy, created_at AS createdAt, resolved_at AS resolvedAt FROM cabin_defects ORDER BY created_at DESC").all(); return Response.json({ defects: rows.results }); }
export async function POST(request: Request) { const user = await getCrewUser(request); if (!user) return unauthorized(); await ensureTable(); const body = await request.json() as Record<string, unknown>; const safety = Boolean(body.safetyHazard); const mel = String(body.melClassification ?? "none"); if (safety && mel === "minimum") return Response.json({ error: "A safety hazard cannot be deferred under Minimum MEL. Engineering action is required." }, { status: 400 }); const required = ["flightNo","aircraftRegistration","equipmentType","defectType","description","cabinLocation"].every((key) => String(body[key] ?? "").trim()); if (!required) return Response.json({ error: "Complete all required defect fields." }, { status: 400 }); const engineerRequired = safety || body.defectType === "Engineering issue" || Boolean(body.engineerRequired); const result = await getDatabase().prepare("INSERT INTO cabin_defects (flight_no, aircraft_registration, equipment_type, defect_type, description, cabin_location, safety_hazard, engineer_required, mel_classification, status, reported_by) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'open', ?)").bind(String(body.flightNo), String(body.aircraftRegistration), String(body.equipmentType), String(body.defectType), String(body.description), String(body.cabinLocation), safety ? 1 : 0, engineerRequired ? 1 : 0, mel, user.fullName).run(); return Response.json({ id: result.meta.last_row_id }, { status: 201 }); }
export async function PATCH(request: Request) { const user = await getCrewUser(request); if (!user) return unauthorized(); await ensureTable(); const body = await request.json() as Record<string, unknown>; const id = Number(body.id); if (!id) return Response.json({ error: "Defect id required" }, { status: 400 }); const database = getDatabase(); const current = await database.prepare("SELECT safety_hazard AS safetyHazard FROM cabin_defects WHERE id = ?").bind(id).first<{ safetyHazard: number }>(); const status = String(body.status ?? "open"); if (current?.safetyHazard && status === "deferred") return Response.json({ error: "Safety hazards cannot be deferred." }, { status: 400 }); const resolvedAt = status === "rectified" ? new Date().toISOString() : null; await database.prepare("UPDATE cabin_defects SET status = ?, engineer_notes = ?, resolved_at = ? WHERE id = ?").bind(status, String(body.engineerNotes ?? ""), resolvedAt, id).run(); return Response.json({ ok: true }); }
