"use client";
import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, MinusCircle, Plus, ShieldCheck, Users, X } from "lucide-react";

type Flight = { flightNo: string; aircraft: string; passengers: number; supervisor: string };
type Plan = { flightNo: string; baseCabinCrew: number; leadCrew: number; additionalCrew: number; doubleCrew: number | boolean; requiredTotal: number };
type Assignment = { id: number; flightNo: string; crewName: string; employeeId: string; assignmentRole: string; status: string };
type User = { id: number; fullName: string; employeeId: string; role: string; station: string };

export function crewRule(aircraft: string) { const normalized = aircraft.toLowerCase().replaceAll(" ", ""); return normalized.includes("a321") ? { type: normalized.includes("neo") ? "A321neo" : "A321", capacity: "201–207", cabin: 5, lead: 1, total: 6 } : { type: "A320", capacity: "180", cabin: 3, lead: 1, total: 4 }; }

export function CrewPlannerModal({ flight, onClose }: { flight: Flight; onClose: () => void }) {
  const rule = crewRule(flight.aircraft); const [plans, setPlans] = useState<Plan[]>([]); const [assignments, setAssignments] = useState<Assignment[]>([]); const [users, setUsers] = useState<User[]>([]); const [additional, setAdditional] = useState(0); const [doubleCrew, setDoubleCrew] = useState(false); const [selectedUser, setSelectedUser] = useState(""); const [role, setRole] = useState("Cabin Crew"); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(() => fetch("/api/crew-planning").then((r) => r.json()).then((data) => { setPlans(data.plans ?? []); setAssignments(data.assignments ?? []); setUsers(data.users ?? []); const plan = data.plans?.find((p: Plan) => p.flightNo === flight.flightNo); if (plan) { setAdditional(plan.additionalCrew); setDoubleCrew(Boolean(plan.doubleCrew)); } }), [flight.flightNo]);
  useEffect(() => { void load(); }, [load]);
  const plan = plans.find((p) => p.flightNo === flight.flightNo); const roster = assignments.filter((a) => a.flightNo === flight.flightNo); const required = (rule.total + additional) * (doubleCrew ? 2 : 1); const filled = roster.length;
  async function savePlan() { setSaving(true); await fetch("/api/crew-planning", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "updatePlan", flightNo: flight.flightNo, additionalCrew: additional, doubleCrew }) }); setSaving(false); await load(); }
  async function assign() { const user = users.find((u) => String(u.id) === selectedUser); if (!user) return setError("Select a registered crew member."); setError(""); const response = await fetch("/api/crew-planning", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "assignCrew", flightNo: flight.flightNo, userId: user.id, crewName: user.fullName, employeeId: user.employeeId, assignmentRole: role }) }); const body = await response.json(); if (!response.ok) return setError(body.error); setSelectedUser(""); await load(); }
  async function remove(id: number) { await fetch(`/api/crew-planning?id=${id}`, { method: "DELETE" }); await load(); }
  return <div className="modal-backdrop"><section className="modal crew-planner-modal"><div className="modal-header"><div><span className="modal-kicker">AIRCRAFT CREW STRUCTURE</span><h2>{flight.flightNo} · {rule.type} crew plan</h2></div><button className="icon-button" onClick={onClose}><X size={20} /></button></div>
    <div className="crew-rule-banner"><ShieldCheck /><div><span>STANDARD COMPLEMENT</span><strong>{rule.cabin} cabin crew + {rule.lead} lead cabin crew</strong><small>{rule.capacity} passenger capacity · approximately 1 crew per 50 passengers</small></div><b>{rule.total}<small>total</small></b></div>
    <div className="crew-plan-controls"><div className="crew-control-block">Additional crew<span>Based on operational requirement</span><div className="inline-stepper"><button aria-label="Remove additional crew" onClick={() => setAdditional(Math.max(0, additional - 1))}>−</button><strong>{additional}</strong><button aria-label="Add additional crew" onClick={() => setAdditional(additional + 1)}>+</button></div></div><div className="double-toggle"><input id="double-crew-operation" type="checkbox" checked={doubleCrew} onChange={(e) => setDoubleCrew(e.target.checked)} /><label htmlFor="double-crew-operation"><strong>Double crew operation</strong><small>Doubles the complete planned complement</small></label></div><div className="required-crew"><span>REQUIRED TOTAL</span><strong>{required}</strong><small>{doubleCrew ? `(${rule.total} + ${additional}) × 2` : `${rule.total} + ${additional}`}</small></div></div>
    <button className="save-plan-button" onClick={savePlan} disabled={saving}>{saving ? "Saving…" : "Save crew requirement"}</button>
    <div className="roster-head"><div><span>ASSIGNED CREW</span><strong>{filled} of {plan?.requiredTotal ?? required} positions filled</strong></div><div className="crew-fill-bar"><i style={{ width: `${Math.min(100, filled / Math.max(1, plan?.requiredTotal ?? required) * 100)}%` }} /></div></div>
    <div className="crew-assign-form"><select value={selectedUser} onChange={(e) => setSelectedUser(e.target.value)}><option value="">Select registered crew member</option>{users.map((user) => <option value={user.id} key={user.id}>{user.fullName} · {user.employeeId} · {user.station}</option>)}</select><select value={role} onChange={(e) => setRole(e.target.value)}><option>Lead Cabin Crew</option><option>Cabin Crew</option><option>Additional Crew</option></select><button onClick={assign}><Plus size={15} /> Assign</button></div>{error && <div className="auth-error">{error}</div>}
    <div className="crew-roster">{roster.map((member) => <div key={member.id}><span className="avatar">{member.crewName.split(" ").map((p) => p[0]).join("").slice(0,2)}</span><span><strong>{member.crewName}</strong><small>{member.employeeId} · {member.assignmentRole}</small></span><em><CheckCircle2 size={14} /> Confirmed</em><button onClick={() => remove(member.id)} aria-label={`Remove ${member.crewName}`}><MinusCircle size={16} /></button></div>)}{!roster.length && <div className="roster-empty"><Users /><span><strong>No crew assigned yet</strong>Use registered cabin crew accounts to fill this roster.</span></div>}</div>
  </section></div>;
}
