"use client";
import { useEffect, useState } from "react";
import { ArrowRight, CheckCircle2, PackageCheck, Plus, Send, Utensils, X } from "lucide-react";
type Handover = { id: number; flightNo: string; department: string; subject: string; notes: string; priority: string; status: string; sentBy: string; recipient: string; createdAt: string };
export function DepartmentHandovers() { const [rows, setRows] = useState<Handover[]>([]); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [form, setForm] = useState({ flightNo: "PA201", department: "Logistics", subject: "", notes: "", priority: "normal" }); const load = () => fetch("/api/department-handovers").then((r) => r.json()).then((d) => setRows(d.handovers ?? [])); useEffect(() => { load(); }, []);
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); const response = await fetch("/api/department-handovers", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); setSaving(false); if (response.ok) { setOpen(false); setForm({ ...form, subject: "", notes: "" }); load(); } }
  async function acknowledge(id: number) { await fetch("/api/department-handovers", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, status: "acknowledged" }) }); load(); }
  return <><div className="department-handover-head"><div className="department-rule"><PackageCheck /><span><strong>Logistics</strong>Cabin stock, equipment and supply movement</span><ArrowRight /><Utensils /><span><strong>Catering</strong>Meals, beverages and galley uplift</span></div><button className="primary-button" onClick={() => setOpen(true)}><Plus size={15} /> New department handover</button></div><section className="ops-card department-handover-list">{rows.map((row) => <article key={row.id}><div className={`department-icon ${row.department.toLowerCase()}`}>{row.department === "Logistics" ? <PackageCheck /> : <Utensils />}</div><div><span>{row.flightNo} · {row.department}</span><strong>{row.subject}</strong><p>{row.notes}</p><small>Sent by {row.sentBy} to {row.recipient}</small></div><div><em className={`priority ${row.priority}`}>{row.priority}</em><small>{new Date(row.createdAt).toLocaleString()}</small>{row.status === "sent" ? <button onClick={() => acknowledge(row.id)}>Acknowledge</button> : <b><CheckCircle2 /> Acknowledged</b>}</div></article>)}{!rows.length && <div className="empty-state"><Send /><strong>No department handovers yet</strong><span>Send logistics and catering information to the responsible department.</span></div>}</section>
    {open && <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-header"><div><span className="modal-kicker">DEPARTMENT HANDOVER</span><h2>Send operational handover</h2></div><button type="button" className="icon-button" onClick={() => setOpen(false)}><X /></button></div><div className="form-grid"><label>Flight number<input required value={form.flightNo} onChange={(e) => setForm({ ...form, flightNo: e.target.value.toUpperCase() })} /></label><label>Department<select value={form.department} onChange={(e) => setForm({ ...form, department: e.target.value })}><option>Logistics</option><option>Catering</option></select></label><label className="full">Subject<input required value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} placeholder={form.department === "Logistics" ? "e.g. Blanket stock transfer" : "e.g. Final meal uplift variance"} /></label><label className="full">Handover notes<textarea required rows={4} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} placeholder="Record quantities, exceptions and actions required…" /></label><label className="full">Priority<select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}><option value="normal">Normal</option><option value="high">High</option><option value="critical">Critical</option></select></label></div><div className="modal-actions"><button type="button" className="ghost-button" onClick={() => setOpen(false)}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? "Sending…" : `Send to ${form.department} Department`}</button></div></form></div>}
  </>;
}
