"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowRight, CheckCircle2, Clock3, Download, FileCheck2, Filter, Gauge, Inbox, MapPin, Plane, Plus, Search, Send, X } from "lucide-react";
import { AppChrome } from "./AppChrome";
import { CrewPlannerModal, crewRule } from "./CrewPlannerModal";
import { DepartmentHandovers } from "./DepartmentHandovers";

type Flight = { flightNo: string; flightDate: string; origin: string; destination: string; departure: string; aircraft: string; registration: string; gate: string; passengers: number; status: string; readiness: number; supervisor: string };
type Handover = { id: number; fromFlightId: string; toFlightNo: string; toRoute: string; toCrew: string; notes: string; status: string; createdAt: string };
type Item = { id: number; required: number; loaded: number; checked: boolean };
type Data = { flights: Flight[]; recentHandovers: Handover[]; items: Item[] };

const emptyData: Data = { flights: [], recentHandovers: [], items: [] };
const statusLabel: Record<string, string> = { turnaround: "Turnaround", briefing: "Crew briefing", scheduled: "Scheduled", delayed: "Delayed", ready: "Ready", departed: "Departed" };

function useOperations() {
  const [data, setData] = useState<Data>(emptyData);
  const [loading, setLoading] = useState(true);
  const refresh = () => fetch("/api/operations").then((r) => r.ok ? r.json() : Promise.reject()).then((next) => { if (Array.isArray(next.flights)) setData(next); }).catch(() => undefined).finally(() => setLoading(false));
  useEffect(() => { refresh(); }, []);
  return { data, setData, refresh, loading };
}

function PageTitle({ eyebrow, title, copy, action }: { eyebrow: string; title: string; copy: string; action?: React.ReactNode }) {
  return <div className="ops-title"><div><span>{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{action}</div>;
}

export function OverviewPage() {
  const { data, loading } = useOperations();
  const current = data.flights.find((flight) => flight.status === "turnaround");
  const checked = data.items.filter((item) => item.checked).length;
  const shortages = data.items.filter((item) => item.loaded < item.required).length;
  return <AppChrome active="Overview"><div className="workspace generic-page">
    <PageTitle eyebrow="SUNDAY · 16 AUGUST" title="Good morning, Sana" copy="Here is the live picture across Islamabad crew operations." action={<Link href="/" className="primary-button"><Plane size={16} /> Open active turnaround</Link>} />
    <section className="kpi-grid">
      <article><span className="kpi-icon blue"><Plane /></span><div><small>TODAY&apos;S FLIGHTS</small><strong>{data.flights.length || "—"}</strong><p>3 departing from ISB</p></div></article>
      <article><span className="kpi-icon green"><CheckCircle2 /></span><div><small>CHECKS COMPLETE</small><strong>{data.items.length ? `${Math.round(checked / data.items.length * 100)}%` : "—"}</strong><p>{checked} requisites verified</p></div></article>
      <article><span className="kpi-icon amber"><AlertTriangle /></span><div><small>OPEN ISSUES</small><strong>{shortages}</strong><p>{shortages ? "Requires action" : "No shortages"}</p></div></article>
      <article><span className="kpi-icon indigo"><Send /></span><div><small>HANDOVERS</small><strong>{data.recentHandovers.length}</strong><p>{data.recentHandovers.filter((h) => h.status === "sent").length} awaiting acknowledgement</p></div></article>
    </section>
    <section className="overview-grid">
      <article className="ops-card active-operation"><div className="card-head"><div><span>ACTIVE OPERATION</span><h2>{current?.flightNo || "PA201"} · {current?.origin || "ISB"} <ArrowRight size={15} /> {current?.destination || "KHI"}</h2></div><span className="live-badge"><i /> Live</span></div><div className="active-flight-body"><div className="large-progress" style={{ "--progress": `${(current?.readiness || 75) * 3.6}deg` } as React.CSSProperties}><strong>{current?.readiness || 75}%</strong><span>ready</span></div><div className="flight-facts"><div><small>DEPARTURE</small><strong>{current?.departure || "11:20"}</strong></div><div><small>GATE</small><strong>{current?.gate || "04"}</strong></div><div><small>PASSENGERS</small><strong>{current?.passengers || 181}</strong></div><div><small>SUPERVISOR</small><strong>{current?.supervisor || "Sana Khan"}</strong></div></div></div><div className="issue-callout"><AlertTriangle size={17} /><span><strong>{shortages} supply shortage open</strong>Resolve before boarding begins.</span><a href="/">Review <ArrowRight size={14} /></a></div></article>
      <article className="ops-card"><div className="card-head"><div><span>SHIFT CONTINUITY</span><h2>Recent handovers</h2></div><a href="/handovers">View all</a></div><div className="activity-list">{data.recentHandovers.slice(0, 4).map((handover) => <div key={handover.id}><div className="activity-icon"><Send size={15} /></div><span><strong>{handover.fromFlightId} → {handover.toFlightNo}</strong><small>{handover.toCrew} · {handover.status}</small></span><time>{new Date(handover.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time></div>)}{loading && <p className="loading-line">Loading operations…</p>}</div></article>
    </section>
    <section className="ops-card schedule-card"><div className="card-head"><div><span>FLIGHT BOARD</span><h2>Upcoming departures</h2></div><a href="/flights">Manage flights <ArrowRight size={14} /></a></div><div className="flight-board">{data.flights.slice(0, 5).map((flight) => <div key={flight.flightNo}><strong>{flight.departure}</strong><span><b>{flight.flightNo}</b><small>{flight.origin} → {flight.destination}</small></span><span><MapPin size={14} /> Gate {flight.gate}</span><span>{flight.aircraft}</span><em className={`flight-status ${flight.status}`}>{statusLabel[flight.status] || flight.status}</em></div>)}</div></section>
  </div></AppChrome>;
}

export function FlightsPage() {
  const { data, setData, refresh } = useOperations();
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [crewFlight, setCrewFlight] = useState<Flight | null>(null);
  const [form, setForm] = useState({ flightNo: "", origin: "ISB", destination: "KHI", departure: "", gate: "", aircraft: "Airbus A320", registration: "", passengers: "", supervisor: "" });
  const flights = data.flights.filter((f) => (filter === "all" || f.status === filter) && `${f.flightNo} ${f.origin} ${f.destination} ${f.supervisor}`.toLowerCase().includes(query.toLowerCase()));
  async function createFlight(event: React.FormEvent) { event.preventDefault(); setSaving(true); const response = await fetch("/api/operations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "createFlight", ...form, passengers: Number(form.passengers) }) }); setSaving(false); if (response.ok) { setOpen(false); await refresh(); } }
  async function changeStatus(flightNo: string, status: string) { setData((d) => ({ ...d, flights: d.flights.map((f) => f.flightNo === flightNo ? { ...f, status } : f) })); await fetch("/api/operations", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ entity: "flight", flightNo, status, readiness: status === "ready" ? 100 : undefined }) }); }
  return <AppChrome active="Flights"><div className="workspace generic-page"><PageTitle eyebrow="OPERATIONS CONTROL" title="Flights" copy="Plan today’s rotations, assign supervisors and track turnaround readiness." action={<button className="primary-button" onClick={() => setOpen(true)}><Plus size={16} /> Add flight</button>} />
    <div className="list-toolbar"><div className="list-search"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search flight, station or supervisor" /></div><div className="filter-select"><Filter size={15} /><select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">All statuses</option><option value="turnaround">Turnaround</option><option value="briefing">Crew briefing</option><option value="scheduled">Scheduled</option><option value="ready">Ready</option><option value="delayed">Delayed</option></select></div></div>
    <section className="ops-card data-card"><table><thead><tr><th>Flight</th><th>Route & departure</th><th>Aircraft</th><th>Crew structure</th><th>Readiness</th><th>Status</th></tr></thead><tbody>{flights.map((flight) => { const rule = crewRule(flight.aircraft); return <tr key={flight.flightNo}><td><strong className="flight-number">{flight.flightNo}</strong><span className="unit">Gate {flight.gate}</span></td><td><strong>{flight.origin} <ArrowRight size={13} /> {flight.destination}</strong><span className="unit">{flight.flightDate} · {flight.departure}</span></td><td><strong>{flight.aircraft}</strong><span className="unit">{flight.registration} · cap. {rule.capacity}</span></td><td><button className="crew-plan-button" onClick={() => setCrewFlight(flight)}><span><b>{rule.total}</b> standard crew</span><small>{rule.cabin} cabin + {rule.lead} lead · Manage</small></button></td><td><div className="readiness-bar"><i style={{ width: `${flight.readiness}%` }} /></div><small>{flight.readiness}%</small></td><td><select className={`status-select ${flight.status}`} value={flight.status} onChange={(e) => changeStatus(flight.flightNo, e.target.value)}><option value="scheduled">Scheduled</option><option value="briefing">Crew briefing</option><option value="turnaround">Turnaround</option><option value="ready">Ready</option><option value="departed">Departed</option><option value="delayed">Delayed</option></select></td></tr>})}</tbody></table>{!flights.length && <div className="empty-state"><Plane /><strong>No flights found</strong><span>Try another search or add a flight.</span></div>}</section>
    {open && <div className="modal-backdrop"><form className="modal flight-modal" onSubmit={createFlight}><div className="modal-header"><div><span className="modal-kicker">FLIGHT PLANNING</span><h2>Add operational flight</h2></div><button type="button" className="icon-button" onClick={() => setOpen(false)}><X size={20} /></button></div><div className="form-grid">{[["Flight number","flightNo","PA209"],["Departure","departure","14:30"],["Origin","origin","ISB"],["Destination","destination","KHI"],["Gate","gate","06"],["Registration","registration","AP-EDA"],["Passengers","passengers","150"],["Supervisor","supervisor","Crew lead"]].map(([label,key,placeholder]) => <label key={key}>{label}<input required={["flightNo","departure","origin","destination"].includes(key)} placeholder={placeholder} value={form[key as keyof typeof form]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>)}<label className="full">Aircraft<select value={form.aircraft} onChange={(e) => setForm({ ...form, aircraft: e.target.value })}><option>Airbus A320</option><option>Airbus A321</option><option>Airbus A321neo</option></select></label></div><div className="modal-actions"><button type="button" className="ghost-button" onClick={() => setOpen(false)}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? "Saving…" : "Create flight"}</button></div></form></div>}
    {crewFlight && <CrewPlannerModal flight={crewFlight} onClose={() => setCrewFlight(null)} />}
  </div></AppChrome>;
}

export function HandoversPage() {
  const { data, setData } = useOperations(); const [filter, setFilter] = useState("all"); const [selected, setSelected] = useState<Handover | null>(null); const [handoverView, setHandoverView] = useState<"crew" | "department">("department");
  const handovers = data.recentHandovers.filter((h) => filter === "all" || h.status === filter);
  async function acknowledge(id: number) { setData((d) => ({ ...d, recentHandovers: d.recentHandovers.map((h) => h.id === id ? { ...h, status: "acknowledged" } : h) })); setSelected((h) => h ? { ...h, status: "acknowledged" } : h); await fetch("/api/operations", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ entity: "handover", id, status: "acknowledged" }) }); }
  return <AppChrome active="Handovers"><div className="workspace generic-page"><PageTitle eyebrow="SHIFT CONTINUITY" title="Handovers" copy="A durable log of outgoing notes, incoming ownership and acknowledgements." action={<Link className="primary-button" href="/"><Send size={16} /> Create from turnaround</Link>} />
    <section className="handover-kpis"><div><Inbox /><span><strong>{data.recentHandovers.filter((h) => h.status === "sent").length}</strong>Awaiting acknowledgement</span></div><div><CheckCircle2 /><span><strong>{data.recentHandovers.filter((h) => h.status === "acknowledged").length}</strong>Acknowledged today</span></div><div><Clock3 /><span><strong>4 min</strong>Average response time</span></div></section>
    <div className="handover-view-tabs"><button className={handoverView === "department" ? "active" : ""} onClick={() => setHandoverView("department")}>Department handovers</button><button className={handoverView === "crew" ? "active" : ""} onClick={() => setHandoverView("crew")}>Crew-to-crew handovers</button></div>
    {handoverView === "department" ? <DepartmentHandovers /> : <>
    <div className="panel-toolbar handover-toolbar"><div className="segmented">{["all","sent","acknowledged"].map((value) => <button key={value} className={filter === value ? "selected" : ""} onClick={() => setFilter(value)}>{value === "all" ? "All handovers" : value}</button>)}</div></div>
    <section className="ops-card handover-list">{handovers.map((h) => <button key={h.id} onClick={() => setSelected(h)}><div className={`handover-direction ${h.status}`}><Send size={18} /></div><div><span>{h.fromFlightId} <ArrowRight size={13} /> {h.toFlightNo}</span><strong>{h.toRoute}</strong><small>{h.notes}</small></div><div><span className={`handover-badge ${h.status}`}>{h.status}</span><small>{new Date(h.createdAt).toLocaleString()}</small><b>{h.toCrew}</b></div></button>)}{!handovers.length && <div className="empty-state"><Inbox /><strong>No handovers here</strong><span>Change the filter to see other records.</span></div>}</section>
    {selected && <div className="modal-backdrop"><section className="modal"><div className="modal-header"><div><span className="modal-kicker">HANDOVER RECORD #{selected.id}</span><h2>{selected.fromFlightId} → {selected.toFlightNo}</h2></div><button className="icon-button" onClick={() => setSelected(null)}><X size={20} /></button></div><div className="handover-route"><div><span>OUTGOING</span><strong>{selected.fromFlightId}</strong><small>Completed sector</small></div><ArrowRight /><div><span>INCOMING</span><strong>{selected.toFlightNo}</strong><small>{selected.toRoute}</small></div></div><div className="record-details"><label>Incoming supervisor<strong>{selected.toCrew}</strong></label><label>Status<span className={`handover-badge ${selected.status}`}>{selected.status}</span></label><label className="full">Operational notes<p>{selected.notes}</p></label><label className="full">Recorded at<strong>{new Date(selected.createdAt).toLocaleString()}</strong></label></div><div className="modal-actions"><button className="ghost-button" onClick={() => setSelected(null)}>Close</button>{selected.status === "sent" && <button className="primary-button" onClick={() => acknowledge(selected.id)}><CheckCircle2 size={16} /> Acknowledge receipt</button>}</div></section></div>}
    </>}
  </div></AppChrome>;
}

export function ReportsPage() {
  const { data } = useOperations(); const [range, setRange] = useState("today");
  const checked = data.items.filter((i) => i.checked).length; const completion = data.items.length ? Math.round(checked / data.items.length * 100) : 0; const shortages = data.items.filter((i) => i.loaded < i.required).length;
  const categories = useMemo(() => [{ label: "Catering", value: 88 }, { label: "Cabin comfort", value: 100 }, { label: "Cabin service", value: 74 }, { label: "Special requests", value: 96 }], []);
  function exportCsv() { const rows = [["Flight","Route","Departure","Status","Readiness"], ...data.flights.map((f) => [f.flightNo,`${f.origin}-${f.destination}`,f.departure,f.status,String(f.readiness)])]; const blob = new Blob([rows.map((r) => r.join(",")).join("\n")], { type: "text/csv" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `bluecrew-report-${range}.csv`; a.click(); URL.revokeObjectURL(url); }
  return <AppChrome active="Reports"><div className="workspace generic-page"><PageTitle eyebrow="PERFORMANCE & COMPLIANCE" title="Reports" copy="Operational readiness, shortage patterns and handover accountability." action={<div className="report-actions"><select value={range} onChange={(e) => setRange(e.target.value)}><option value="today">Today</option><option value="7-days">Last 7 days</option><option value="30-days">Last 30 days</option></select><button className="primary-button" onClick={exportCsv}><Download size={16} /> Export CSV</button></div>} />
    <section className="kpi-grid report-kpis"><article><span className="kpi-icon green"><Gauge /></span><div><small>AVG. READINESS</small><strong>{data.flights.length ? Math.round(data.flights.reduce((a,f) => a + f.readiness, 0) / data.flights.length) : 0}%</strong><p>Across {data.flights.length} flights</p></div></article><article><span className="kpi-icon blue"><FileCheck2 /></span><div><small>CHECK COMPLETION</small><strong>{completion}%</strong><p>{checked}/{data.items.length} items</p></div></article><article><span className="kpi-icon amber"><AlertTriangle /></span><div><small>SHORTAGE RATE</small><strong>{data.items.length ? Math.round(shortages / data.items.length * 100) : 0}%</strong><p>{shortages} affected item</p></div></article><article><span className="kpi-icon indigo"><Clock3 /></span><div><small>HANDOVER SLA</small><strong>96%</strong><p>Within 5 minutes</p></div></article></section>
    <section className="reports-grid"><article className="ops-card"><div className="card-head"><div><span>READINESS BY CATEGORY</span><h2>Checklist performance</h2></div></div><div className="horizontal-chart">{categories.map((c) => <div key={c.label}><span>{c.label}</span><div><i style={{ width: `${c.value}%` }} /></div><strong>{c.value}%</strong></div>)}</div></article><article className="ops-card"><div className="card-head"><div><span>ISSUE DISTRIBUTION</span><h2>Operational exceptions</h2></div></div><div className="donut-wrap"><div className="donut"><strong>{shortages + 3}</strong><span>issues</span></div><div className="legend"><span><i className="blue" /> Catering <b>50%</b></span><span><i className="amber" /> Cabin <b>25%</b></span><span><i className="red" /> Special requests <b>25%</b></span></div></div></article></section>
    <section className="ops-card data-card"><div className="card-head"><div><span>FLIGHT PERFORMANCE</span><h2>Readiness register</h2></div></div><table><thead><tr><th>Flight</th><th>Route</th><th>Supervisor</th><th>Status</th><th>Readiness</th></tr></thead><tbody>{data.flights.map((f) => <tr key={f.flightNo}><td><strong>{f.flightNo}</strong></td><td>{f.origin} → {f.destination}</td><td>{f.supervisor}</td><td><span className={`flight-status ${f.status}`}>{statusLabel[f.status] || f.status}</span></td><td><div className="score-cell"><div className="readiness-bar"><i style={{ width: `${f.readiness}%` }} /></div><b>{f.readiness}%</b></div></td></tr>)}</tbody></table></section>
  </div></AppChrome>;
}
