import { getCrewUser, unauthorized } from "../../../db/auth";
import { getDatabase } from "../../../db";

async function ensureTable() { const database = getDatabase(); await database.batch([
  database.prepare(`CREATE TABLE IF NOT EXISTS department_handovers (id INTEGER PRIMARY KEY AUTOINCREMENT, flight_no TEXT NOT NULL, department TEXT NOT NULL, subject TEXT NOT NULL, notes TEXT NOT NULL, priority TEXT NOT NULL DEFAULT 'normal', status TEXT NOT NULL DEFAULT 'sent', sent_by TEXT NOT NULL, recipient TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
  database.prepare(`CREATE INDEX IF NOT EXISTS idx_department_handovers_flight_no ON department_handovers(flight_no)`),
  database.prepare(`CREATE INDEX IF NOT EXISTS idx_department_handovers_department_status ON department_handovers(department, status)`),
]); }
export async function GET(request: Request) { const user = await getCrewUser(request); if (!user) return unauthorized(); await ensureTable(); const rows = await getDatabase().prepare("SELECT id, flight_no AS flightNo, department, subject, notes, priority, status, sent_by AS sentBy, recipient, created_at AS createdAt FROM department_handovers ORDER BY created_at DESC").all(); return Response.json({ handovers: rows.results }); }
export async function POST(request: Request) { const user = await getCrewUser(request); if (!user) return unauthorized(); await ensureTable(); const body = await request.json() as Record<string, unknown>; const department = String(body.department ?? ""); if (!["Logistics", "Catering"].includes(department)) return Response.json({ error: "Choose Logistics or Catering" }, { status: 400 }); const flightNo = String(body.flightNo ?? ""); const subject = String(body.subject ?? "").trim(); const notes = String(body.notes ?? "").trim(); if (!flightNo || !subject || !notes) return Response.json({ error: "Flight, subject and notes are required" }, { status: 400 }); const recipient = department === "Logistics" ? "Logistics Department" : "Catering Department"; const result = await getDatabase().prepare("INSERT INTO department_handovers (flight_no, department, subject, notes, priority, status, sent_by, recipient) VALUES (?, ?, ?, ?, ?, 'sent', ?, ?)").bind(flightNo, department, subject, notes, String(body.priority ?? "normal"), user.fullName, recipient).run(); return Response.json({ id: result.meta.last_row_id }, { status: 201 }); }
export async function PATCH(request: Request) { const user = await getCrewUser(request); if (!user) return unauthorized(); await ensureTable(); const body = await request.json() as { id?: number; status?: string }; if (!body.id) return Response.json({ error: "Handover id required" }, { status: 400 }); await getDatabase().prepare("UPDATE department_handovers SET status = ? WHERE id = ?").bind(body.status === "acknowledged" ? "acknowledged" : "sent", body.id).run(); return Response.json({ ok: true }); }
